#!/bin/bash
# 剑桥少儿英语拼写练习应用启动脚本

echo "🌟 剑桥少儿英语拼写练习应用"
echo ""
echo "应用已启动并运行在:"
echo "🌐 地址: http://localhost:8001"
echo ""
echo "📋 功能特性:"
echo "• 70+ 剑桥少儿英语1-2级单词"
echo "• 卡通Q版界面设计"
echo "• 学习进度统计"
echo "• 实时错误反馈"
echo "• 离线使用能力"
echo ""
echo "🎨 界面优化:"
echo "• 统一按钮大小"
echo "• 精准错误提示"
echo "• 完整单词展示"
echo "• 更大提示文字"
echo ""
echo "💡 使用说明:"
echo "1. 打开浏览器访问 http://localhost:8001"
echo "2. 查看中文提示"
echo "3. 点击字母按钮拼写单词"
echo "4. 点击提交按钮检查结果"
echo "5. 点击'下一个单词'继续练习"
echo ""
echo "🔧 如需重启服务，请运行:"
echo "   pkill -f start_server_new.py && cd /home/admin/.openclaw/workspace/agents/代码虾/项目/剑桥少儿英语拼写练习/frontend && python3 start_server_new.py > frontend.log 2>&1 &"
echo ""
echo "📖 服务信息:"
echo "   PID: $(pgrep -f start_server_new.py)"
echo "   端口: 8001"
echo "   目录: /home/admin/.openclaw/workspace/agents/代码虾/项目/剑桥少儿英语拼写练习/frontend/public"
echo ""
echo "✅ 应用正在运行"